# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nielsjohandewit/Dev/visualizersdotnl/cookiedough/code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nielsjohandewit/Dev/visualizersdotnl/cookiedough

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nielsjohandewit/Dev/visualizersdotnl/cookiedough/CMakeFiles /Users/nielsjohandewit/Dev/visualizersdotnl/cookiedough//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nielsjohandewit/Dev/visualizersdotnl/cookiedough/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cookiedough

# Build rule for target.
cookiedough: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cookiedough
.PHONY : cookiedough

# fast build rule for target.
cookiedough/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/build
.PHONY : cookiedough/fast

3rdparty/rocket-stripped/lib/device.o: 3rdparty/rocket-stripped/lib/device.c.o
.PHONY : 3rdparty/rocket-stripped/lib/device.o

# target to build an object file
3rdparty/rocket-stripped/lib/device.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/3rdparty/rocket-stripped/lib/device.c.o
.PHONY : 3rdparty/rocket-stripped/lib/device.c.o

3rdparty/rocket-stripped/lib/device.i: 3rdparty/rocket-stripped/lib/device.c.i
.PHONY : 3rdparty/rocket-stripped/lib/device.i

# target to preprocess a source file
3rdparty/rocket-stripped/lib/device.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/3rdparty/rocket-stripped/lib/device.c.i
.PHONY : 3rdparty/rocket-stripped/lib/device.c.i

3rdparty/rocket-stripped/lib/device.s: 3rdparty/rocket-stripped/lib/device.c.s
.PHONY : 3rdparty/rocket-stripped/lib/device.s

# target to generate assembly for a file
3rdparty/rocket-stripped/lib/device.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/3rdparty/rocket-stripped/lib/device.c.s
.PHONY : 3rdparty/rocket-stripped/lib/device.c.s

3rdparty/rocket-stripped/lib/track.o: 3rdparty/rocket-stripped/lib/track.c.o
.PHONY : 3rdparty/rocket-stripped/lib/track.o

# target to build an object file
3rdparty/rocket-stripped/lib/track.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/3rdparty/rocket-stripped/lib/track.c.o
.PHONY : 3rdparty/rocket-stripped/lib/track.c.o

3rdparty/rocket-stripped/lib/track.i: 3rdparty/rocket-stripped/lib/track.c.i
.PHONY : 3rdparty/rocket-stripped/lib/track.i

# target to preprocess a source file
3rdparty/rocket-stripped/lib/track.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/3rdparty/rocket-stripped/lib/track.c.i
.PHONY : 3rdparty/rocket-stripped/lib/track.c.i

3rdparty/rocket-stripped/lib/track.s: 3rdparty/rocket-stripped/lib/track.c.s
.PHONY : 3rdparty/rocket-stripped/lib/track.s

# target to generate assembly for a file
3rdparty/rocket-stripped/lib/track.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/3rdparty/rocket-stripped/lib/track.c.s
.PHONY : 3rdparty/rocket-stripped/lib/track.c.s

audio.o: audio.cpp.o
.PHONY : audio.o

# target to build an object file
audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/audio.cpp.o
.PHONY : audio.cpp.o

audio.i: audio.cpp.i
.PHONY : audio.i

# target to preprocess a source file
audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/audio.cpp.i
.PHONY : audio.cpp.i

audio.s: audio.cpp.s
.PHONY : audio.s

# target to generate assembly for a file
audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/audio.cpp.s
.PHONY : audio.cpp.s

ball.o: ball.cpp.o
.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i
.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s
.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/ball.cpp.s
.PHONY : ball.cpp.s

boxblur.o: boxblur.cpp.o
.PHONY : boxblur.o

# target to build an object file
boxblur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/boxblur.cpp.o
.PHONY : boxblur.cpp.o

boxblur.i: boxblur.cpp.i
.PHONY : boxblur.i

# target to preprocess a source file
boxblur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/boxblur.cpp.i
.PHONY : boxblur.cpp.i

boxblur.s: boxblur.cpp.s
.PHONY : boxblur.s

# target to generate assembly for a file
boxblur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/boxblur.cpp.s
.PHONY : boxblur.cpp.s

demo.o: demo.cpp.o
.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i
.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s
.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/demo.cpp.s
.PHONY : demo.cpp.s

display.o: display.cpp.o
.PHONY : display.o

# target to build an object file
display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/display.cpp.o
.PHONY : display.cpp.o

display.i: display.cpp.i
.PHONY : display.i

# target to preprocess a source file
display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/display.cpp.i
.PHONY : display.cpp.i

display.s: display.cpp.s
.PHONY : display.s

# target to generate assembly for a file
display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/display.cpp.s
.PHONY : display.cpp.s

fast-cosine.o: fast-cosine.cpp.o
.PHONY : fast-cosine.o

# target to build an object file
fast-cosine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/fast-cosine.cpp.o
.PHONY : fast-cosine.cpp.o

fast-cosine.i: fast-cosine.cpp.i
.PHONY : fast-cosine.i

# target to preprocess a source file
fast-cosine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/fast-cosine.cpp.i
.PHONY : fast-cosine.cpp.i

fast-cosine.s: fast-cosine.cpp.s
.PHONY : fast-cosine.s

# target to generate assembly for a file
fast-cosine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/fast-cosine.cpp.s
.PHONY : fast-cosine.cpp.s

fx-blitter.o: fx-blitter.cpp.o
.PHONY : fx-blitter.o

# target to build an object file
fx-blitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/fx-blitter.cpp.o
.PHONY : fx-blitter.cpp.o

fx-blitter.i: fx-blitter.cpp.i
.PHONY : fx-blitter.i

# target to preprocess a source file
fx-blitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/fx-blitter.cpp.i
.PHONY : fx-blitter.cpp.i

fx-blitter.s: fx-blitter.cpp.s
.PHONY : fx-blitter.s

# target to generate assembly for a file
fx-blitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/fx-blitter.cpp.s
.PHONY : fx-blitter.cpp.s

gamepad.o: gamepad.cpp.o
.PHONY : gamepad.o

# target to build an object file
gamepad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/gamepad.cpp.o
.PHONY : gamepad.cpp.o

gamepad.i: gamepad.cpp.i
.PHONY : gamepad.i

# target to preprocess a source file
gamepad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/gamepad.cpp.i
.PHONY : gamepad.cpp.i

gamepad.s: gamepad.cpp.s
.PHONY : gamepad.s

# target to generate assembly for a file
gamepad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/gamepad.cpp.s
.PHONY : gamepad.cpp.s

image.o: image.cpp.o
.PHONY : image.o

# target to build an object file
image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/image.cpp.o
.PHONY : image.cpp.o

image.i: image.cpp.i
.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s
.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/image.cpp.s
.PHONY : image.cpp.s

landscape.o: landscape.cpp.o
.PHONY : landscape.o

# target to build an object file
landscape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/landscape.cpp.o
.PHONY : landscape.cpp.o

landscape.i: landscape.cpp.i
.PHONY : landscape.i

# target to preprocess a source file
landscape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/landscape.cpp.i
.PHONY : landscape.cpp.i

landscape.s: landscape.cpp.s
.PHONY : landscape.s

# target to generate assembly for a file
landscape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/landscape.cpp.s
.PHONY : landscape.cpp.s

lens.o: lens.cpp.o
.PHONY : lens.o

# target to build an object file
lens.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/lens.cpp.o
.PHONY : lens.cpp.o

lens.i: lens.cpp.i
.PHONY : lens.i

# target to preprocess a source file
lens.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/lens.cpp.i
.PHONY : lens.cpp.i

lens.s: lens.cpp.s
.PHONY : lens.s

# target to generate assembly for a file
lens.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/lens.cpp.s
.PHONY : lens.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/main.cpp.s
.PHONY : main.cpp.s

polar.o: polar.cpp.o
.PHONY : polar.o

# target to build an object file
polar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/polar.cpp.o
.PHONY : polar.cpp.o

polar.i: polar.cpp.i
.PHONY : polar.i

# target to preprocess a source file
polar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/polar.cpp.i
.PHONY : polar.cpp.i

polar.s: polar.cpp.s
.PHONY : polar.s

# target to generate assembly for a file
polar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/polar.cpp.s
.PHONY : polar.cpp.s

random.o: random.cpp.o
.PHONY : random.o

# target to build an object file
random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i
.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s
.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/random.cpp.s
.PHONY : random.cpp.s

rocket.o: rocket.cpp.o
.PHONY : rocket.o

# target to build an object file
rocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/rocket.cpp.o
.PHONY : rocket.cpp.o

rocket.i: rocket.cpp.i
.PHONY : rocket.i

# target to preprocess a source file
rocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/rocket.cpp.i
.PHONY : rocket.cpp.i

rocket.s: rocket.cpp.s
.PHONY : rocket.s

# target to generate assembly for a file
rocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/rocket.cpp.s
.PHONY : rocket.cpp.s

satori-lumablur.o: satori-lumablur.cpp.o
.PHONY : satori-lumablur.o

# target to build an object file
satori-lumablur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/satori-lumablur.cpp.o
.PHONY : satori-lumablur.cpp.o

satori-lumablur.i: satori-lumablur.cpp.i
.PHONY : satori-lumablur.i

# target to preprocess a source file
satori-lumablur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/satori-lumablur.cpp.i
.PHONY : satori-lumablur.cpp.i

satori-lumablur.s: satori-lumablur.cpp.s
.PHONY : satori-lumablur.s

# target to generate assembly for a file
satori-lumablur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/satori-lumablur.cpp.s
.PHONY : satori-lumablur.cpp.s

shadertoy.o: shadertoy.cpp.o
.PHONY : shadertoy.o

# target to build an object file
shadertoy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/shadertoy.cpp.o
.PHONY : shadertoy.cpp.o

shadertoy.i: shadertoy.cpp.i
.PHONY : shadertoy.i

# target to preprocess a source file
shadertoy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/shadertoy.cpp.i
.PHONY : shadertoy.cpp.i

shadertoy.s: shadertoy.cpp.s
.PHONY : shadertoy.s

# target to generate assembly for a file
shadertoy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/shadertoy.cpp.s
.PHONY : shadertoy.cpp.s

shared-resources.o: shared-resources.cpp.o
.PHONY : shared-resources.o

# target to build an object file
shared-resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/shared-resources.cpp.o
.PHONY : shared-resources.cpp.o

shared-resources.i: shared-resources.cpp.i
.PHONY : shared-resources.i

# target to preprocess a source file
shared-resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/shared-resources.cpp.i
.PHONY : shared-resources.cpp.i

shared-resources.s: shared-resources.cpp.s
.PHONY : shared-resources.s

# target to generate assembly for a file
shared-resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/shared-resources.cpp.s
.PHONY : shared-resources.cpp.s

sincos-lut.o: sincos-lut.cpp.o
.PHONY : sincos-lut.o

# target to build an object file
sincos-lut.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/sincos-lut.cpp.o
.PHONY : sincos-lut.cpp.o

sincos-lut.i: sincos-lut.cpp.i
.PHONY : sincos-lut.i

# target to preprocess a source file
sincos-lut.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/sincos-lut.cpp.i
.PHONY : sincos-lut.cpp.i

sincos-lut.s: sincos-lut.cpp.s
.PHONY : sincos-lut.s

# target to generate assembly for a file
sincos-lut.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/sincos-lut.cpp.s
.PHONY : sincos-lut.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/tests.cpp.s
.PHONY : tests.cpp.s

torus-twister.o: torus-twister.cpp.o
.PHONY : torus-twister.o

# target to build an object file
torus-twister.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/torus-twister.cpp.o
.PHONY : torus-twister.cpp.o

torus-twister.i: torus-twister.cpp.i
.PHONY : torus-twister.i

# target to preprocess a source file
torus-twister.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/torus-twister.cpp.i
.PHONY : torus-twister.cpp.i

torus-twister.s: torus-twister.cpp.s
.PHONY : torus-twister.s

# target to generate assembly for a file
torus-twister.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/torus-twister.cpp.s
.PHONY : torus-twister.cpp.s

tunnelscape.o: tunnelscape.cpp.o
.PHONY : tunnelscape.o

# target to build an object file
tunnelscape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/tunnelscape.cpp.o
.PHONY : tunnelscape.cpp.o

tunnelscape.i: tunnelscape.cpp.i
.PHONY : tunnelscape.i

# target to preprocess a source file
tunnelscape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/tunnelscape.cpp.i
.PHONY : tunnelscape.cpp.i

tunnelscape.s: tunnelscape.cpp.s
.PHONY : tunnelscape.s

# target to generate assembly for a file
tunnelscape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/tunnelscape.cpp.s
.PHONY : tunnelscape.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cookiedough.dir/build.make CMakeFiles/cookiedough.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cookiedough"
	@echo "... 3rdparty/rocket-stripped/lib/device.o"
	@echo "... 3rdparty/rocket-stripped/lib/device.i"
	@echo "... 3rdparty/rocket-stripped/lib/device.s"
	@echo "... 3rdparty/rocket-stripped/lib/track.o"
	@echo "... 3rdparty/rocket-stripped/lib/track.i"
	@echo "... 3rdparty/rocket-stripped/lib/track.s"
	@echo "... audio.o"
	@echo "... audio.i"
	@echo "... audio.s"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... boxblur.o"
	@echo "... boxblur.i"
	@echo "... boxblur.s"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... fast-cosine.o"
	@echo "... fast-cosine.i"
	@echo "... fast-cosine.s"
	@echo "... fx-blitter.o"
	@echo "... fx-blitter.i"
	@echo "... fx-blitter.s"
	@echo "... gamepad.o"
	@echo "... gamepad.i"
	@echo "... gamepad.s"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
	@echo "... landscape.o"
	@echo "... landscape.i"
	@echo "... landscape.s"
	@echo "... lens.o"
	@echo "... lens.i"
	@echo "... lens.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... polar.o"
	@echo "... polar.i"
	@echo "... polar.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... rocket.o"
	@echo "... rocket.i"
	@echo "... rocket.s"
	@echo "... satori-lumablur.o"
	@echo "... satori-lumablur.i"
	@echo "... satori-lumablur.s"
	@echo "... shadertoy.o"
	@echo "... shadertoy.i"
	@echo "... shadertoy.s"
	@echo "... shared-resources.o"
	@echo "... shared-resources.i"
	@echo "... shared-resources.s"
	@echo "... sincos-lut.o"
	@echo "... sincos-lut.i"
	@echo "... sincos-lut.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
	@echo "... torus-twister.o"
	@echo "... torus-twister.i"
	@echo "... torus-twister.s"
	@echo "... tunnelscape.o"
	@echo "... tunnelscape.i"
	@echo "... tunnelscape.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

